### PR TITLE
add predict example

### PR DESCRIPTION
**Pull request by Shellbye**
Since there is no prediction example, I added one at the end of the training.

### CODE REVIEW

**Comment by alexander-rakhlin** [comment]
Thanks. 
1) Could you please move ACTION = "predict" into top, settings section?
2) Prediction must verify presence of weight file and load it.
2a) You can save it in 'word2vec_models' dir and rename it into 'models'. Please update path in w2v.py too
3) Just curious, is there convention for adding extra spaces in conditional expressions? Do you use an automated tool for  formatting?
`if len(filter_sizes)>1`

**Comment by Shellbye** [comment]
1. I just added the predict example, and the `ACTION = "predict"` is for my future work, so I did not pull request it. If you want it, of course I can do that.

2. Prediction can perform both when training is over and load weights file.
    2a) Same as 1. , I just did not pull request it.

3. I don't understand. Are you asking about code format? If yes, I use Pycharm. Then what is the meaning of `if len(filter_sizes)>1`?

**Comment by Shellbye** [comment]
My faults, I don't realize that continue commit is still in the pull request. I will fix it. ^_^

**Comment by alexander-rakhlin** [comment]
If ACTION is anything but "train", model remains uninitialized, it does not load weights file.

**Comment by Shellbye** [comment]
OK, I fixed it as you mentioned.

**Pull request merged**
